project_id = "uvqrdzwimiszqkmyzbvf"

[functions.fetch-stock-data]
verify_jwt = false

[functions.fetch-options-data]
verify_jwt = false

[functions.analyze-stocks]
verify_jwt = false

[functions.fetch-fundamentals]
verify_jwt = false

[functions.analyze-fundamentals]
verify_jwt = false
